steps:
  # Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # Build the Docker image using Cloud Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/protean-tome-429613-s0/olympicgo", "."]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/protean-tome-429613-s0/olympicgo"]

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "olympicgo",
        "--image",
        "gcr.io/protean-tome-429613-s0/olympicgo",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/protean-tome-429613-s0/olympicgo"
